#!/usr/bin/env python3
"""
auth
"""
from flask import request
from typing import List, TypeVar


class Auth:
    """
    class docc
    """

    def require_auth(self, path: str, excluded_paths: List[str]) -> bool:
        '''
            salut lbnet
        '''
        if path and not (path in excluded_paths or path + "/" in excluded_paths) or (excluded_paths is None or excluded_paths == []):
            return True
        else:
            return False

    def authorization_header(self, request=None) -> str:
        """
        alaa khir
        """
        return None

    def current_user(self, request=None) -> TypeVar('User'):
        """
        nyes"""
        return None
